---
---
- name: Configure Elk VM with Docker
  hosts: elkservers
  remote_user: Red_Team_Admin
  become: true
  tasks:
    # Use apt module
  - name: Install docker.io
    apt:
      force_apt_get: yes
      name: docker.io
      state: present

    # Use apt module
  - name: Install python-pip
    apt:
      force_apt_get: yes
      name: python-pip
      state: present

    # Use pip module
  - name: Install Docker python module
    pip:
      name: docker
      state: present

    # Use command module
  - name: Increase virtual memory
    command: sudo sysctl -w vm.max_map_count=262144

    # Use docker_container module
  - name: download and launch a docker elk container
    docker_container:
      name: elk
      image: sebp/elk
      state: started
    # Please list the ports that ELK runs on
      published_ports:
        - 5601:5601
        - 9200:9200
        - 5044:5044
